### PR TITLE
Smashing magazine

### PR DESCRIPTION
**Pull request by SantiagoGuerra**

### CODE REVIEW

**Comment by SantiagoGuerra** [comment]
Hi @stratospherique , i don't understand this code review, can you explain with line code please?

Thank you!

**Comment by stratospherique** [comment]
> Hi @stratospherique , i don't understand this code review, can you explain with line code please?
> 
> Thank you!

Those are requirements that you need to implement in you project. Namely, you are required to use `article` tag instead of `div` tag inside each row. And there is the markup (html file) that you need to check using a validator and fix all the errors that it might return.

**Comment by SantiagoGuerra** [comment]
I would like to see the line code to have a better view, because  we use `article` element 

Thank you

**Comment by SantiagoGuerra** [comment]
Thank you very much @stratospherique , i just was confused because i have a lot  `div` and `articles elements`, but with this explanation now i am sure

**Pull request merged**
